### ISSUE TITLE
Storm UI showing improper values for Kafka Trident

### ISSUE THREAD

**Issue by dmakshay** [miguno/kafka-storm-starter#5]
I have been trying with trident topology for Kafka i.e. TransactionalTridentKafkaSpout. All works fine except the Storm UI. Even though I've not produced any data to my topic, the Storm UI keeps showing invalid emitted/transferred values. Meaning the count keeps on increasing even when there is no data in the topic. I've tried deleting the data/logs stored in zookeeper, storm, kafka and recreate kafka topics and also have set
topology.stats.sample.rate: 1.0 

Here is my configuration and source code snippet:

``` java
 final Config config = new Config();
    config.put(Config.TOPOLOGY_TRIDENT_BATCH_EMIT_INTERVAL_MILLIS, 3000);
    config.setNumWorkers(2);
    config.put(Config.NIMBUS_HOST, "192.168.125.20");
    config.put(Config.NIMBUS_THRIFT_PORT, 6627);
    config.put(Config.STORM_ZOOKEEPER_PORT, 2181);
    config.put(Config.STORM_ZOOKEEPER_SERVERS, Arrays.asList("192.168.125.20"));
    config.put(Config.TOPOLOGY_EXECUTOR_RECEIVE_BUFFER_SIZE, 16384);
    config.put(Config.TOPOLOGY_ACKER_EXECUTORS, 1);
    config.put(Config.TOPOLOGY_MAX_SPOUT_PENDING, 10);
    config.put(Config.DRPC_SERVERS, Arrays.asList("192.168.125.20"));
    config.put(Config.DRPC_PORT, 3772);

final BrokerHosts zkHosts = new ZkHosts("192.168.125.20");
final TridentKafkaConfig kafkaConfig = new TridentKafkaConfig(zkHosts, "Test_Topic", "");
kafkaConfig.scheme = new SchemeAsMultiScheme(new StringScheme());
kafkaConfig.bufferSizeBytes = 1024 * 1024 * 4;
kafkaConfig.fetchSizeBytes = 1024 * 1024 * 4;
kafkaConfig.forceFromStart = false;

final TransactionalTridentKafkaSpout kafkaSpout = new TransactionalTridentKafkaSpout(kafkaConfig);
final TridentTopology topology = new TridentTopology();
topology.newStream("spout", kafkaSpout)
       .each(new Fields("str"), new TestFunction(), new Fields("test"))
       .each(new Fields("str"), new PrintFilter());
```

**Comment by miguno** [comment]
This might be an issue of Storm itself.  May I suggest sending a note to the [Storm mailing list](http://storm.apache.org/documentation/Home.html)?

**Comment by miguno** [comment]
I assume you were also the person asking the question [Storm UI improper values and Capillary tool](http://stackoverflow.com/questions/30600789/storm-ui-improper-values-and-capillary-tool) on StackOverflow a few days ago?

**Comment by miguno** [comment]
I checked the screenshot in the SO question -- the numbers for emitted/transferred are pretty low.  Are you possibly seeing the what I'd call the [UI metric artifacts of Trident](http://qnalist.com/questions/5172389/trident-kafka-spout-ack-count-increasing-even-though-no-messages-are-processed), which -- as mentioned in the SO thread -- creates its own tuples behind the scenes, which also show up in the Storm UI?

> Trident executes a batch every 500ms (by default). A batch involves a bunch
> of coordination messages going out to all the bolts to coordinate the batch
> (even if the batch is empty). So that's what you're seeing.
> 
> (source: [Trident Kafka Spout - Ack Count Increasing Even Though No Messages Are Processed](http://qnalist.com/questions/5172389/trident-kafka-spout-ack-count-increasing-even-though-no-messages-are-processed))

**Comment by dmakshay** [comment]
@miguno Thanks so much for your reply. True I did post in SO. Yes probably that is what I am seeing in the UI. Is there a way to get the actual number of messages emitted/processed leaving out the coordination message counts as asked in the link you menioned?

**Comment by dmakshay** [comment]
@miguno As you said, I've asked in the storm user group. If I get any answers I'll post here.

**Comment by miguno** [comment]
>  Is there a way to get the actual number of messages emitted/processed leaving out the coordination message counts as asked in the link you menioned?

I am not aware of any way to filter the numbers.
