### ISSUE TITLE
we have setup all the tunning params for kafka and strom still getting very high latency

### ISSUE THREAD

**Issue by imvipul** [miguno/kafka-storm-starter#7]
we have 3 node kafka cluster....3 node zookeeper and 1 node storm cluster with 8 CPU per node....there is enough memory and disk space available...we are using kafkaspout ...for testing we have a topology with two spout reading message from two topics and sending it to bolt which is outputting it to kafka topic....we are facing very high latency

**Comment by miguno** [comment]
@imvipul I am afraid that support for Storm/Kafka is out of scope for this code project. :-(
